spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: agora-account
            uri: http://agora-account:8080
            predicates:
              - Path=/login/**, /members/**, /account/**
            metadata:
              cors:
                allowedOrigins: 'http://localhost:3000'
                allow-credentials: true
                allowedMethods:
                  - GET
                  - POST
                  - DELETE
                  - UPDATE
                  - OPTIONS
                allowedHeaders: '*'
                maxAge: 30
          - id: agora-main
            uri: http://agora-main:8081
            predicates:
              - Path=/**
            metadata:
              cors:
                allowedOrigins: 'http://localhost:3000'
                allow-credentials: true
                allowedMethods:
                  - GET
                  - POST
                  - DELETE
                  - UPDATE
                  - OPTIONS
                allowedHeaders: '*'
                maxAge: 30
server:
  port: 8088


